<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11299" started-at="2017-09-01T14:51:13Z" finished-at="2017-09-01T14:51:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11299" started-at="2017-09-01T14:51:13Z" finished-at="2017-09-01T14:51:24Z">
      <class name="com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser@1e397ed7]" name="setUp" is-config="true" duration-ms="10064" started-at="2017-09-01T20:21:13Z" finished-at="2017-09-01T20:21:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginWithExistingUser(java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser@1e397ed7]" name="loginWithExistingUser" duration-ms="0" started-at="2017-09-01T20:21:24Z" data-provider="login" finished-at="2017-09-01T20:21:24Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.lang.Object[][] com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser.getTestData() must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser.getTestData() must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithExistingUser -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser@1e397ed7]" name="tear" is-config="true" duration-ms="628" started-at="2017-09-01T20:21:24Z" finished-at="2017-09-01T20:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.test.automation.UIautomation.Homepage.VerifyloginWithExistingUser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
